FROM       golang:1.6.2-alpine
MAINTAINER BehanceRE <qa-behance@adobe.com>

# install runtime scripts
ADD . $GOPATH/src/github.com/behance/ecr-login


RUN apk update && \
    apk add \
      bash \
      build-base \
      curl \
      make \
      git \
    && rm -rf /var/cache/apk/* 
 
WORKDIR $GOPATH/src/github.com/behance/ecr-login

RUN  make build 
 

CMD  ./ecr-login 
